// Generated by CoffeeScript 1.4.0
var get, set;

get = Em.get;

set = Em.set;

module.exports = Em.CollectionView.extend({
  size: 5,
  rating: 2,
  tagName: "ul",
  init: function() {
    var rating;
    this._super();
    rating = get(this, "rating");
    return set(this, "actualRating", rating);
  },
  itemViewClass: require("ember-select").extend({
    template: Em.Handlebars.compile(""),
    mouseEnter: function() {
      return this._();
    },
    mouseLeave: function() {
      var rating;
      rating = get(this, "parentView.actualRating");
      return set(this, "parentView.rating", rating);
    },
    click: function() {
      var rating;
      rating = get(this, "parentView.rating");
      set(this, "parentView.actualRating", rating);
      return this._();
    },
    _: function() {
      var content, parentViewContent;
      content = get(this, "content");
      parentViewContent = get(this, "parentView.content");
      return set(this, "parentView.rating", 1 + parentViewContent.indexOf(content));
    }
  }),
  classNames: ["component", "rating"],
  checked: (function() {
    var rating, _i, _ref, _results;
    rating = get(this, "rating");
    if (rating === 0) {
      return [];
    } else {
      return (function() {
        _results = [];
        for (var _i = 0, _ref = rating - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; 0 <= _ref ? _i++ : _i--){ _results.push(_i); }
        return _results;
      }).apply(this);
    }
  }).property("rating"),
  content: (function() {
    var size, _i, _results;
    size = get(this, "size");
    if (size === 0) {
      [];
    } else {

    }
    return (function() {
      _results = [];
      for (var _i = 0; 0 <= size ? _i <= size : _i >= size; 0 <= size ? _i++ : _i--){ _results.push(_i); }
      return _results;
    }).apply(this);
  }).property("size")
});
